### ISSUE TITLE
temp.couple/preindustrial, and DAIS temp normalization

### ISSUE THREAD

**Issue by tonyewong** [scrim-network/BRICK#19]
BRICK_coupledModel.R -- 

-- change "temp.couple" name to "temp.preindustrial", which should match what's coming out of DOECLIM or SNEASY. Do NOT modify/normalize to other periods. Should be relative to 1850-1870.

-- instead, (for GIS/SIMPLE), just normalize within the function call, or create a dummy array (e.g. "temp.simple") to match the proper normalization for each submodel. (SIMPLE is the only one that requires temperatures that are not preindustrial, at the moment)

-- make sure DAIS is taking in temperatures relative to 1850-1870 mean temperature 

-- make it clear in the comments at the beginning of the routine what "temp.preindustrial" is relative to

**Comment by bvegawe** [comment]
Pull request up!
