### ISSUE TITLE
adaptMCMC v1.3 complains about gamma of 0.5

### ISSUE THREAD

**Issue by bvegawe** [scrim-network/BRICK#30]
In 1.3, gamma must be (0.5,1.0]. Should we go to 0.501 or something?

**Comment by tonyewong** [comment]
I believe 0.66 is the recommended gamma, but if 0.501 or so works then
that's a faster adaptation and would be nice. Slower can avoid
over-adapting to local posterior modes and getting stuck. If lower works,
then go with that, but 0.66 is a good justifiable value too.

Cheers,

Tony

Tony Wong
Dept of Computer Science
University of Colorado Boulder
anthony.e.wong@colorado.edu
tonyewong.github.io

**Comment by tonyewong** [comment]
Changed to 0.51 in the DAIS and BRICK calibration drivers for default.
